# Generated by Django 5.1 on 2024-08-16 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
